apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # 您可以选择一个未使用的端口，通常在 30000-32767 范围内

